AUG:
  COLOR_JITTER: 0.4
DATA:
  BATCH_SIZE: 1024
  DATA_PATH: "../data/"
  DATASET: "cifar10"
  IMG_SIZE: 32 
MODEL:
  NAME: resnet18
  NUM_CLASSES: 10
  DROP_RATE: 0.0
TRAIN:
  EPOCHS: 100
  WARMUP_EPOCHS: 20
  LR: 3e-4
  MIN_LR: 3e-5
  WARMUP_LR: 3e-5
  LR_SCHEDULER:
    NAME: "cosine"
  OPTIMIZER:
    NAME: "adamw"
    EPS: 1e-8
    BETAS: (0.9, 0.999)
    MOMENTUM: 0.9
OUTPUT: "output/resnet18"
SAVE_FREQ: 50 
PRINT_FREQ: 500